# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_7ge5YpZCpFWXtiEtPyCK166x1lUqaH-
"""

import gdown
def trainedweights():
  output = 'trained.pth'
  gdown. download('https://drive.google.com/uc?id=1-58Yo7ufnAIIvSEf9apoM77KzhOoiKMQ', output, quiet=False)